######### llm_args #########
model: gpt-3.5-turbo-0125
temperature: 0.0
top_p: 0.7
n: 1
max_tokens: 1024

######### data_args #########
dataset_name: DATASET NAME
prompt_name: zero-shot-cot

use_core_instruction: true

dataset_filepath: /path/to/datafile
output_filepath: /path/to/save

######### running_args #########
generate_log_file: true
is_number_extraction: false
